# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6cf3797db6b81ef63955f3a5da701e9366a27e0042e0d4ca481cefa1338466b3e618bc2d3c11138293eb972f043a8c717f2ddd3d76edd552fd038636291e7d2

test:
  secret_key_base: 0c81f64cfc14c51bfd260c19fa0d08df49c31ef90a217d7a59771520681ad63596ac5b9fa8dde310f6b0c507273933842c97b2dfc43c207ab7aab42fb7e68c90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
